/* This file was generated by blade */
extern "C" {
namespace binary_version {
extern const int kSvnInfoCount = 1;
extern const char* const kSvnInfo[1] = {"commit 2f90e2e20c830f7bb2b8966b3ccabefea800ccee\n"
"Author: myp-Ubuntu <manyanpeng@hotmail.com>\n"
"Date:   Sun May 20 01:13:05 2018 -0700\n"
"\n"
"    test11\n"
""};
extern const char kBuildType[] = "release";
extern const char kBuildTime[] = "Fri Jun  1 00:58:27 2018";
extern const char kBuilderName[] = "myp";
extern const char kHostName[] = "ubuntu";
extern const char kCompiler[] = "GCC 5.4.0";
}}
